"""
kb_colombia.py — Base de conocimiento de Colombia para el submodelo informal.
Fuente de verdad para generar corpus; los datos completos para RESPONDER
viven espejados en backend/api/lib/kb_colombia.php (PHP responde, Python
solo clasifica).
"""

# ── 32 departamentos + capital ────────────────────────────────────────────────
DEPARTMENTS = {
    'amazonas':              {'capital': 'Leticia',                'region': 'Amazonía'},
    'antioquia':             {'capital': 'Medellín',               'region': 'Andina'},
    'arauca':                {'capital': 'Arauca',                 'region': 'Orinoquía'},
    'atlantico':             {'capital': 'Barranquilla',           'region': 'Caribe'},
    'bolivar':               {'capital': 'Cartagena',              'region': 'Caribe'},
    'boyaca':                {'capital': 'Tunja',                  'region': 'Andina'},
    'caldas':                {'capital': 'Manizales',              'region': 'Andina'},
    'caqueta':               {'capital': 'Florencia',              'region': 'Amazonía'},
    'casanare':              {'capital': 'Yopal',                  'region': 'Orinoquía'},
    'cauca':                 {'capital': 'Popayán',                'region': 'Andina'},
    'cesar':                 {'capital': 'Valledupar',             'region': 'Caribe'},
    'choco':                 {'capital': 'Quibdó',                 'region': 'Pacífico'},
    'cordoba':               {'capital': 'Montería',               'region': 'Caribe'},
    'cundinamarca':          {'capital': 'Bogotá',                 'region': 'Andina'},
    'guainia':               {'capital': 'Inírida',                'region': 'Amazonía'},
    'guaviare':              {'capital': 'San José del Guaviare',  'region': 'Amazonía'},
    'huila':                 {'capital': 'Neiva',                  'region': 'Andina'},
    'la guajira':            {'capital': 'Riohacha',               'region': 'Caribe'},
    'guajira':               {'capital': 'Riohacha',               'region': 'Caribe'},
    'magdalena':             {'capital': 'Santa Marta',            'region': 'Caribe'},
    'meta':                  {'capital': 'Villavicencio',          'region': 'Orinoquía'},
    'narino':                {'capital': 'Pasto',                  'region': 'Andina'},
    'nariño':                {'capital': 'Pasto',                  'region': 'Andina'},
    'norte de santander':    {'capital': 'Cúcuta',                 'region': 'Andina'},
    'putumayo':              {'capital': 'Mocoa',                  'region': 'Amazonía'},
    'quindio':               {'capital': 'Armenia',                'region': 'Andina'},
    'risaralda':             {'capital': 'Pereira',                'region': 'Andina'},
    'san andres':            {'capital': 'San Andrés',             'region': 'Insular'},
    'san andres y providencia': {'capital': 'San Andrés',          'region': 'Insular'},
    'santander':             {'capital': 'Bucaramanga',            'region': 'Andina'},
    'sucre':                 {'capital': 'Sincelejo',              'region': 'Caribe'},
    'tolima':                {'capital': 'Ibagué',                 'region': 'Andina'},
    'valle':                 {'capital': 'Cali',                   'region': 'Pacífico'},
    'valle del cauca':       {'capital': 'Cali',                   'region': 'Pacífico'},
    'vaupes':                {'capital': 'Mitú',                   'region': 'Amazonía'},
    'vichada':               {'capital': 'Puerto Carreño',         'region': 'Orinoquía'},
}

# ── Presidentes de Colombia (republicanos + Gran Colombia + recientes) ────────
PRESIDENTS = {
    'simon bolivar':        'El Libertador — primer presidente de la Gran Colombia (1819-1830), artífice de la independencia.',
    'francisco de paula santander': 'El Hombre de las Leyes — vicepresidente de la Gran Colombia y organizador de la república.',
    'antonio narino':       'Antonio Nariño — traductor de los Derechos del Hombre, precursor de la independencia; Bogotá.',
    'rafael nunez':         'Rafael Núñez — impulsor de la Constitución de 1886, la que rigió por más de un siglo.',
    'jose eustasio rivera': None,  # no es presidente (escritor) — no incluir
    'alfonso lopez pumarejo': 'López Pumarejo — dos veces presidente (1934-38, 1942-45), "Revolución en Marcha".',
    'gustavo rojas pinilla':'Rojas Pinilla — único golpe militar del siglo XX colombiano (1953-57).',
    'alberto lleras camargo':'Lleras Camargo — fundador del Frente Nacional (1958), la alternancia Liberal-Conservadora.',
    'guillermo leon valencia':'Guillermo León Valencia — conservador, 1962-66.',
    'carlos lleras restrepo':'Lleras Restrepo — 1966-70, reforma agraria y gran desarrollo institucional.',
    'miguel antonio caro':  'Miguel Antonio Caro — coautor de la Constitución de 1886.',
    'julio cesar turbay':   'Turbay Ayala — 1978-82, el Estatuto de Seguridad.',
    'belisario betancur':   'Belisario Betancur — 1982-86, paz con los grupos armados y "sí puedo".',
    'virgilio barco':       'Virgilio Barco — 1986-90, apertura y Constituyente.',
    'cesar gaviria':        'César Gaviria — 1990-94, padre de la Constitución de 1991.',
    'ernesto samper':       'Ernesto Samper — 1994-98.',
    'andres pastrana':      'Andrés Pastrana — 1998-2002, el Caguán.',
    'alvaro uribe':         'Álvaro Uribe Vélez — 2002-10, seguridad democrática; dos períodos.',
    'juan manuel santos':   'Juan Manuel Santos — 2010-18, acuerdo de paz con las FARC, Nobel de Paz 2016.',
    'ivan duque':           'Iván Duque — 2018-22.',
    'gustavo petro':        'Gustavo Petro — presidente desde 2022, primer presidente de izquierda.',
    'laureano gomez':       'Laureano Gómez — 1950-53, conservador en época de La Violencia.',
    'mariano ospina perez': 'Ospina Pérez — 1946-50, presidente durante el Bogotazo.',
    'enrique olaya herrera':'Olaya Herrera — 1930-34, primer liberal tras la hegemonía conservadora.',
    'rafael reyes':         'Rafael Reyes — 1904-09, reconstrucción tras la guerra de los Mil Días.',
}
PRESIDENTS = {k: v for k, v in PRESIDENTS.items() if v}

# ── Geografía ─────────────────────────────────────────────────────────────────
GEOGRAPHY = {
    'rio mas largo':         'El río Magdalena — 1.528 km, la arteria histórica del país.',
    'rio principal':         'El río Magdalena, que cruza Colombia de sur a norte.',
    'montaña mas alta':      'El Pico Cristóbal Colón en la Sierra Nevada de Santa Marta — 5.775 m.',
    'pico mas alto':         'El Pico Cristóbal Colón (5.775 m) — Sierra Nevada de Santa Marta.',
    'oceanos':               'Colombia es el único país suramericano con costas en el Atlántico y el Pacífico.',
    'regiones':              'Seis regiones naturales: Caribe, Pacífico, Andina, Orinoquía, Amazonía e Insular.',
    'cordilleras':           'La cordillera de los Andes se divide en tres en Colombia: Occidental, Central y Oriental.',
    'amazonia':              'La Amazonía colombiana cubre ~40% del territorio — el pulmón verde del sur.',
    'orinoquia':             'La Orinoquía — llanos orientales, ganadería y el joropo.',
    'sierra nevada':         'La Sierra Nevada de Santa Marta es la montaña costera más alta del mundo.',
    'desierto':              'El desierto de La Guajira y la Tatacoa en el Huila.',
    'islas':                 'El archipiélago de San Andrés, Providencia y Santa Catalina — mar de los siete colores.',
}

# ── Historia ──────────────────────────────────────────────────────────────────
HISTORY = {
    'independencia':         '20 de julio de 1810 — el grito de independencia en Bogotá; la independencia se selló en Boyacá el 7 de agosto de 1819.',
    'batalla de boyaca':     'El 7 de agosto de 1819 Bolívar derrotó al ejército realista en el Puente de Boyacá — el día que selló la independencia.',
    'gran colombia':         'La Gran Colombia (1819-1831) unió lo que hoy es Colombia, Venezuela, Ecuador y Panamá.',
    'separacion de panama':  'Panamá se separó de Colombia el 3 de noviembre de 1903.',
    'bogotazo':              'El 9 de abril de 1948, el asesinato de Jorge Eliécer Gaitán incendió Bogotá — el Bogotazo.',
    'frente nacional':       '1958-1974: alternancia Liberal-Conservadora pactada tras la dictadura de Rojas Pinilla.',
    'constitucion 1991':     'La Constitución de 1991 — la actual carta política, que declaró a Colombia Estado Social de Derecho.',
    'acuerdo de paz':        'El acuerdo de 2016 con las FARC puso fin a más de 50 años de conflicto armado.',
    'la violencia':          'La Violencia (1948-1958) — la guerra civil bipartidista que marcó el siglo XX.',
    'guerra de los mil dias':'La Guerra de los Mil Días (1899-1902) — última gran guerra civil entre liberales y conservadores.',
    'colonizacion':          'Santa Marta (1525) fue la primera ciudad fundada por españoles en territorio continental.',
    'el dorado':             'La leyenda de El Dorado nació del ritual muisca del cacique bañado en oro en la laguna de Guatavita.',
}

# ── Cultura ───────────────────────────────────────────────────────────────────
CULTURE = {
    'vallenato':             'El vallenato — acordeón, caja y guacharaca; Patrimonio de la Humanidad (UNESCO 2015).',
    'cumbia':                'La cumbia — ritmo fundacional de Colombia, nacido de la fusión indígena y africana.',
    'carnaval de barranquilla': 'El Carnaval de Barranquilla — el más grande de Colombia, Patrimonio UNESCO.',
    'feria de las flores':   'La Feria de las Flores de Medellín — silleteros y Antioquia en su máximo esplendor.',
    'carnaval de negros':    'El Carnaval de Negros y Blancos de Pasto — el primero declarado Patrimonio UNESCO.',
    'gabriel garcia marquez':'Gabriel García Márquez — Nobel de Literatura 1982, Cien Años de Soledad, el realismo mágico.',
    'fernando botero':       'Fernando Botero — el maestro del volumen, esculturas y pinturas conocidas en el mundo.',
    'bandeja paisa':         'La bandeja paisa — fríjoles, arroz, chicharrón, huevo, aguacate y más; plato antioqueño.',
    'ajiaco':                'El ajiaco santafereño — la sopa emblemática de Bogotá: pollo, papas, mazorca y alcaparras.',
    'cafe':                  'El café colombiano — Patrimonio Cultural Inmaterial UNESCO (Eje Cafetero).',
    'esmeraldas':            'Colombia produce las esmeraldas más finas del mundo — Muzo y Chivor, Boyacá.',
    'san agustin':           'El parque arqueológico de San Agustín (Huila) — esculturas precolombinas milenarias, UNESCO.',
    'tejo':                  'El tejo — deporte nacional: lanzar discos a pólvora. La versión colombiana del boliche.',
    'shakira':               'Shakira — de Barranquilla para el mundo, la artista colombiana más global.',
    'eganzo bernal':         'Egan Bernal — primer colombiano y latinoamericano en ganar el Tour de Francia (2019).',
    'egan bernal':           'Egan Bernal — primer colombiano y latinoamericano en ganar el Tour de Francia (2019).',
    'nairo quintana':        'Nairo Quintana — campeón del Giro de Italia y la Vuelta a España; boyacense.',
    'james rodriguez':       'James Rodríguez — goleador del Mundial 2014, el "10" cucuteño.',
    'willys':                'El Jeep Willys — vehículo emblema del Eje Cafetero, ícono cultural.',
    'sombrero vueltiao':     'El sombrero vueltiao — tejido zenú de Córdoba y Sucre, símbolo nacional.',
}

# ── Datos curiosos ────────────────────────────────────────────────────────────
FUN_FACTS = [
    'Colombia es el país con más especies de aves del mundo: más de 1.900 registradas — el 20% de todas las del planeta.',
    'La Sierra Nevada de Santa Marta es la montaña costera más alta del mundo — nieves perpetuas a 42 km del mar Caribe.',
    'Colombia tiene dos océanos: es el único país de Sudamérica con costas en el Pacífico y el Atlántico.',
    'El Caño Cristales, en el Meta, es llamado "el río de los cinco colores" por sus algas que pintan el agua.',
    'Bogotá está a 2.640 metros de altura — más alto que muchas capitales europeas.',
    'El río Amazonas toca Colombia por 117 km — el país tiene una ventana al Amazonas en Leticia.',
    'La palabra " Colombia" suena en más de 50 tipos de música: cumbia, vallenato, salsa, champeta, mapalé, currulao…',
    'El Cerrejón, en La Guajira, es una de las minas de carbón a cielo abierto más grandes del mundo.',
    'La leyenda de El Dorado nació en la laguna de Guatavita, donde los muiscas hacían ofrendas de oro.',
    'Colombia es el segundo país más biodiverso del mundo después de Brasil — primero per cápita.',
    'El Carnaval de Barranquilla dura 4 días pero se prepara todo el año.',
    'La bandera amarilla es el doble de ancha: el amarillo representa el oro y las riquezas de la patria.',
    'El himno nacional tiene 11 estrofas — una de las más largas del mundo.',
    'Medellín inventó el metro en Colombia — el único sistema de metro del país.',
    'El oro de los Quimbayas fue regalado a España y se exhibe en el Museo de América de Madrid.',
    'La guadua, el bambú colombiano, es uno de los materiales de construcción más resistentes del mundo.',
    'Chingaza es uno de los páramos más importantes — le da agua a Bogotá.',
    'El ajiaco santafereño lleva tres tipos de papa: criolla, pastusa y sabanera.',
    'El carnaval de Negros y Blancos de Pasto celebra la abolición de la esclavitud.',
    'Bogotá fue llamada "la Atenas suramericana" en el siglo XIX por su producción intelectual.',
    'El frailejón solo crece en páramos — y Colombia tiene el 50% de los páramos del mundo.',
    'Colombia es el tercer productor mundial de café — el café de Juan Valdez es el ícono.',
    'El ecuador no pasa por Colombia — pero el país está a un paso: Leticia está a 4° de latitud sur.',
    'El Día de las Velitas (7 de diciembre) abre la temporada navideña — millones de velas en las calles.',
    'La Marimba de Currulao del Pacífico es Patrimonio de la Humanidad.',
    'El Dorado era un hombre, no una ciudad: el cacique muisca cubierto de oro en polvo.',
    'Puerto Carreño, en el Vichada, tiene más caimanes que personas en temporada seca.',
    'El sombrero vueltiao puede tener hasta 31 vueltas — más vueltas, más fino.',
    'Colombia es el primer exportador mundial de flores frescas después de Países Bajos.',
    'La piedra del Peñol tiene 740 escalones y una de las vistas más famosas de Antioquia.',
    'San Basilio de Palenque fue el primer pueblo libre de esclavos en América (1603).',
    'El español de Colombia es considerado uno de los más neutros del continente.',
    'El Ciclovía de Bogotá cierra 127 km de calles cada domingo — la más grande del mundo.',
    'El Tiple es el instrumento nacional de Colombia — una guitarra pequeña de 12 cuerdas.',
    'Las empanadas colombianas llevan guiso de papa y carne — cada región tiene su versión.',
    'La misma cantidad de energía que usa Bogotá en un día, el Cerrejón la mueve en carbón en minutos.',
    'Los muelles de Puerto Colombia (Barranquilla) fueron los más largos del mundo en el siglo XIX.',
    'Colombia tiene más de 80 pueblos indígenas que hablan 65 lenguas distintas.',
    'La Laguna de la Cocha (Nariño) tiene una isla santuario que es reserva natural.',
    'Fernando Botero donó 208 obras al Museo de Antioquia — una de las donaciones de arte más grandes de Latinoamérica.',
]

CITIES = {
    'bogota':          'Bogotá — capital del país, ~8 millones de habitantes, a 2.640 m de altura.',
    'medellin':        'Medellín — capital de Antioquia, ciudad de la eterna primavera, ~2.5 millones.',
    'cali':            'Santiago de Cali — capital del Valle, capital mundial de la salsa.',
    'barranquilla':    'Barranquilla — la Arenosa, puerta de oro, casa del Carnaval.',
    'cartagena':       'Cartagena de Indias — la ciudad amurallada, Patrimonio UNESCO.',
    'bucaramanga':     'Bucaramanga — ciudad bonita, capital de Santander.',
    'pereira':         'Pereira — capital de Risaralda, corazón del Eje Cafetero.',
    'manizales':       'Manizales — ciudad de puertas abiertas, capital de Caldas.',
    'armenia':         'Armenia — capital del Quindío, milagro cafetero.',
    'ibague':          'Ibagué — la ciudad musical de Colombia, capital del Tolima.',
    'neiva':           'Neiva — capital del Huila, en el río Magdalena.',
    'villavicencio':   'Villavicencio — la puerta del llano, capital del Meta.',
    'cucuta':          'Cúcuta — capital de Norte de Santander, frontera con Venezuela.',
    'pasto':           'Pasto — capital de Nariño, la sorpresa, ciudad del Carnaval de Negros y Blancos.',
    'santa marta':     'Santa Marta — la ciudad más antigua de Sudamérica (1525).',
    'valledupar':      'Valledupar — capital del Cesar, cuna del vallenato.',
    'monteria':        'Montería — capital de Córdoba, la ronda del Sinú.',
    'sincelejo':       'Sincelejo — capital de Sucre, corazón de los corralejas.',
    'riohacha':        'Riohacha — capital de La Guajira, puerta del desierto.',
    'yopal':           'Yopal — capital de Casanare, tierra del llano.',
    'arauca':          'Arauca — capital del departamento homónimo, frontera con Venezuela.',
    'mocoa':           'Mocoa — capital del Putumayo.',
    'florencia':       'Florencia — capital del Caquetá, puerta a la Amazonía.',
    'leticia':         'Leticia — la triple frontera con Brasil y Perú, capital del Amazonas.',
    'quibdo':          'Quibdó — capital del Chocó, una de las ciudades más lluviosas del mundo.',
    'inirida':         'Inírida — capital del Guainía.',
    'mitu':            'Mitú — capital del Vaupés.',
    'puerto carreno':  'Puerto Carreño — capital del Vichada, la última orilla del Orinoco.',
    'tunja':           'Tunja — capital de Boyacá, ciudad de la independencia.',
    'popayan':         'Popayán — la ciudad blanca, capital del Cauca.',
    'san andres':      'San Andrés — mar de los siete colores, islas del Caribe.',
    'san jose del guaviare': 'San José del Guaviare — puerta a la selva.',
    'villavo':         'Villavicencio — la puerta del llano.',
    'medellin':        'Medellín — capital de Antioquia, ciudad de la eterna primavera.',
    'guatavita':       'Guatavita — la laguna de la leyenda de El Dorado, Cundinamarca.',
    'villa de leyva':  'Villa de Leyva — Boyacá, plaza empedrada más grande de Colombia.',
    'mompox':          'Santa Cruz de Mompox — Bolívar, joya colonial a orillas del Magdalena.',
}
