<?php
/**
 * lib/kb_colombia.php — Conocimiento de Colombia para el chatbot.
 * Espejo de backend/nlu/kb_colombia.py. PHP responde, Python solo clasifica.
 */

const NX_KB_DEPTS = [
    'amazonas' => ['Leticia', 'Amazonía'], 'antioquia' => ['Medellín', 'Andina'],
    'arauca' => ['Arauca', 'Orinoquía'], 'atlantico' => ['Barranquilla', 'Caribe'],
    'bolivar' => ['Cartagena', 'Caribe'], 'boyaca' => ['Tunja', 'Andina'],
    'caldas' => ['Manizales', 'Andina'], 'caqueta' => ['Florencia', 'Amazonía'],
    'casanare' => ['Yopal', 'Orinoquía'], 'cauca' => ['Popayán', 'Andina'],
    'cesar' => ['Valledupar', 'Caribe'], 'choco' => ['Quibdó', 'Pacífico'],
    'cordoba' => ['Montería', 'Caribe'], 'cundinamarca' => ['Bogotá', 'Andina'],
    'guainia' => ['Inírida', 'Amazonía'], 'guaviare' => ['San José del Guaviare', 'Amazonía'],
    'huila' => ['Neiva', 'Andina'], 'la guajira' => ['Riohacha', 'Caribe'],
    'guajira' => ['Riohacha', 'Caribe'], 'magdalena' => ['Santa Marta', 'Caribe'],
    'meta' => ['Villavicencio', 'Orinoquía'], 'narino' => ['Pasto', 'Andina'],
    'nariño' => ['Pasto', 'Andina'], 'norte de santander' => ['Cúcuta', 'Andina'],
    'putumayo' => ['Mocoa', 'Amazonía'], 'quindio' => ['Armenia', 'Andina'],
    'risaralda' => ['Pereira', 'Andina'], 'san andres' => ['San Andrés', 'Insular'],
    'san andres y providencia' => ['San Andrés', 'Insular'],
    'santander' => ['Bucaramanga', 'Andina'], 'sucre' => ['Sincelejo', 'Caribe'],
    'tolima' => ['Ibagué', 'Andina'], 'valle' => ['Cali', 'Pacífico'],
    'valle del cauca' => ['Cali', 'Pacífico'], 'vaupes' => ['Mitú', 'Amazonía'],
    'vichada' => ['Puerto Carreño', 'Orinoquía'],
];

const NX_KB_PRESIDENTS = [
    'simon bolivar' => 'El Libertador — primer presidente de la Gran Colombia (1819-1830), artífice de la independencia.',
    'francisco de paula santander' => 'El Hombre de las Leyes — organizador de la república.',
    'antonio narino' => 'Antonio Nariño — traductor de los Derechos del Hombre, precursor de la independencia.',
    'rafael nunez' => 'Rafael Núñez — impulsor de la Constitución de 1886.',
    'alfonso lopez pumarejo' => 'López Pumarejo — dos veces presidente, «Revolución en Marcha».',
    'gustavo rojas pinilla' => 'Rojas Pinilla — único golpe militar del siglo XX (1953-57).',
    'alberto lleras camargo' => 'Lleras Camargo — fundador del Frente Nacional (1958).',
    'guillermo leon valencia' => 'Guillermo León Valencia — conservador, 1962-66.',
    'carlos lleras restrepo' => 'Lleras Restrepo — 1966-70, reforma agraria.',
    'miguel antonio caro' => 'Miguel Antonio Caro — coautor de la Constitución de 1886.',
    'julio cesar turbay' => 'Turbay Ayala — 1978-82, el Estatuto de Seguridad.',
    'belisario betancur' => 'Belisario Betancur — 1982-86, la paz y el «sí puedo».',
    'virgilio barco' => 'Virgilio Barco — 1986-90.',
    'cesar gaviria' => 'César Gaviria — 1990-94, padre de la Constitución de 1991.',
    'ernesto samper' => 'Ernesto Samper — 1994-98.',
    'andres pastrana' => 'Andrés Pastrana — 1998-2002.',
    'alvaro uribe' => 'Álvaro Uribe Vélez — 2002-10, seguridad democrática.',
    'juan manuel santos' => 'Juan Manuel Santos — 2010-18, acuerdo de paz, Nobel de Paz 2016.',
    'ivan duque' => 'Iván Duque — 2018-22.',
    'laureano gomez' => 'Laureano Gómez — 1950-53.',
    'mariano ospina perez' => 'Ospina Pérez — 1946-50, presidente durante el Bogotazo.',
    'enrique olaya herrera' => 'Olaya Herrera — 1930-34.',
    'rafael reyes' => 'Rafael Reyes — 1904-09, reconstrucción tras los Mil Días.',
];

const NX_KB_GEOGRAPHY = [
    'rio mas largo' => 'El río Magdalena — 1.528 km, la arteria histórica del país.',
    'rio principal' => 'El río Magdalena cruza Colombia de sur a norte.',
    'montaña mas alta' => 'El Pico Cristóbal Colón — 5.775 m, Sierra Nevada de Santa Marta.',
    'pico mas alto' => 'El Pico Cristóbal Colón (5.775 m).',
    'oceanos' => 'Colombia es el único país suramericano con costas en el Atlántico y el Pacífico.',
    'regiones' => 'Seis regiones: Caribe, Pacífico, Andina, Orinoquía, Amazonía e Insular.',
    'cordilleras' => 'Los Andes se dividen en tres en Colombia: Occidental, Central y Oriental.',
    'amazonia' => 'La Amazonía cubre ~40% del territorio colombiano.',
    'orinoquia' => 'La Orinoquía — llanos orientales, ganadería y joropo.',
    'sierra nevada' => 'La Sierra Nevada de Santa Marta — la montaña costera más alta del mundo.',
    'desierto' => 'La Guajira y el desierto de la Tatacoa (Huila).',
    'islas' => 'San Andrés, Providencia y Santa Catalina — el mar de los siete colores.',
];

const NX_KB_HISTORY = [
    'independencia' => '20 de julio de 1810 — el grito de independencia; sellada en Boyacá el 7 de agosto de 1819.',
    'batalla de boyaca' => '7 de agosto de 1819 — Bolívar derrotó a los realistas en el Puente de Boyacá.',
    'gran colombia' => 'La Gran Colombia (1819-1831) unió Colombia, Venezuela, Ecuador y Panamá.',
    'separacion de panama' => 'Panamá se separó de Colombia el 3 de noviembre de 1903.',
    'bogotazo' => '9 de abril de 1948 — el asesinato de Gaitán incendió Bogotá.',
    'frente nacional' => '1958-1974: alternancia Liberal-Conservadora tras la dictadura.',
    'constitucion 1991' => 'La Constitución de 1991 declaró a Colombia Estado Social de Derecho — es la vigente, promulgada por la Asamblea Constituyente que lideró César Gaviria.',
    'ultima constitucion' => 'La Constitución vigente es la de 1991 — Estado Social de Derecho, tutela y derechos fundamentales.',
    'constitucion politica' => 'La Constitución Política vigente es la de 1991 — reemplazó la de 1886.',
    'constitucion actual' => 'La Constitución actual de Colombia es la de 1991.',
    'constitucion de 1886' => 'La Constitución de 1886 rigió el país por más de un siglo hasta la de 1991.',
    'acuerdo de paz' => 'El acuerdo de 2016 con las FARC cerró 50+ años de conflicto.',
    'la violencia' => 'La Violencia (1948-1958) — la guerra civil bipartidista.',
    'guerra de los mil dias' => 'La Guerra de los Mil Días (1899-1902).',
    'colonizacion' => 'Santa Marta (1525) — primera ciudad fundada por españoles en territorio continental.',
    'el dorado' => 'El Dorado — el ritual muisca del cacique bañado en oro en la laguna de Guatavita.',
    'leyenda del dorado' => 'La leyenda de El Dorado: el cacique muisca se cubría de polvo de oro y se sumergía en la laguna de Guatavita ofrendando tesoros. Los conquistadores la buscaron por décadas — era un hombre, no una ciudad.',
    'dorado' => 'El Dorado — el ritual muisca del cacique cubierto de oro en Guatavita; la leyenda que volvió locos a los conquistadores.',
];

const NX_KB_CULTURE = [
    'vallenato' => 'El vallenato — acordeón, caja y guacharaca; Patrimonio UNESCO 2015.',
    'cumbia' => 'La cumbia — ritmo fundacional, fusión indígena y africana.',
    'carnaval de barranquilla' => 'El Carnaval de Barranquilla — Patrimonio UNESCO.',
    'feria de las flores' => 'La Feria de las Flores de Medellín — silleteros y Antioquia.',
    'carnaval de negros' => 'El Carnaval de Negros y Blancos de Pasto — Patrimonio UNESCO.',
    'gabriel garcia marquez' => 'Gabo — Nobel de Literatura 1982, Cien Años de Soledad.',
    'fernando botero' => 'Botero — el maestro del volumen, de Medellín al mundo.',
    'bandeja paisa' => 'La bandeja paisa — fríjoles, chicharrón, huevo, aguacate y más.',
    'ajiaco' => 'El ajiaco santafereño — pollo, tres papas, mazorca y alcaparras.',
    'cafe' => 'El café colombiano — Patrimonio Inmaterial UNESCO (Eje Cafetero).',
    'esmeraldas' => 'Las esmeraldas más finas del mundo — Muzo y Chivor, Boyacá.',
    'san agustin' => 'San Agustín (Huila) — esculturas precolombinas milenarias, UNESCO.',
    'tejo' => 'El tejo — deporte nacional: disco y pólvora.',
    'shakira' => 'Shakira — de Barranquilla para el mundo.',
    'egan bernal' => 'Egan Bernal — primer latinoamericano en ganar el Tour de Francia (2019).',
    'nairo quintana' => 'Nairo Quintana — campeón del Giro y la Vuelta; boyacense.',
    'james rodriguez' => 'James Rodríguez — goleador del Mundial 2014.',
    'sombrero vueltiao' => 'El sombrero vueltiao — tejido zenú, símbolo nacional.',
];

const NX_KB_FACTS = [
    'Colombia es el país con más especies de aves del mundo: +1.900 registradas.',
    'La Sierra Nevada de Santa Marta es la montaña costera más alta del mundo.',
    'Colombia es el único país suramericano con costas en dos océanos.',
    'El Caño Cristales (Meta) es "el río de los cinco colores" por sus algas.',
    'Bogotá está a 2.640 m — más alto que muchas capitales europeas.',
    'El Carnaval de Barranquilla se prepara todo el año.',
    'El amarillo de la bandera es el doble de ancho — representa el oro.',
    'El himno nacional tiene 11 estrofas — de los más largos del mundo.',
    'Medellín tiene el único metro de Colombia.',
    'La leyenda de El Dorado nació en la laguna de Guatavita.',
    'Colombia tiene el 50% de los páramos del mundo — el frailejón solo crece ahí.',
    'Colombia es tercer productor mundial de café.',
    'El 7 de diciembre, las Velitas abren la Navidad — millones de velas en las calles.',
    'San Basilio de Palenque fue el primer pueblo libre de América (1603).',
    'La Ciclovía de Bogotá cierra 127 km cada domingo — la más grande del mundo.',
    'El Tiple es el instrumento nacional — guitarra pequeña de 12 cuerdas.',
    'Colombia tiene +80 pueblos indígenas y 65 lenguas.',
    'La Piedra del Peñol tiene 740 escalones.',
    'Botero donó 208 obras al Museo de Antioquia.',
    'El español colombiano es de los más neutros del continente.',
    'Los muelles de Puerto Colombia fueron los más largos del mundo en el s. XIX.',
    'Colombia es el segundo país más biodiverso — primero per cápita.',
    'El Dorado era un hombre, no una ciudad: el cacique muisca cubierto de oro.',
    'El sombrero vueltiao puede tener 31 vueltas — más vueltas, más fino.',
    'La laguna de la Cocha (Nariño) tiene una isla santuario.',
    'Villa de Leyva tiene la plaza empedrada más grande de Colombia.',
];

const NX_KB_CITIES = [
    'bogota' => 'Bogotá — capital del país, ~8 millones, a 2.640 m de altura.',
    'medellin' => 'Medellín — capital de Antioquia, ciudad de la eterna primavera.',
    'cali' => 'Santiago de Cali — capital del Valle, capital mundial de la salsa.',
    'barranquilla' => 'Barranquilla — la Arenosa, casa del Carnaval.',
    'cartagena' => 'Cartagena de Indias — la ciudad amurallada, UNESCO.',
    'bucaramanga' => 'Bucaramanga — la ciudad bonita, capital de Santander.',
    'pereira' => 'Pereira — corazón del Eje Cafetero.',
    'manizales' => 'Manizales — ciudad de puertas abiertas.',
    'armenia' => 'Armenia — milagro cafetero, capital del Quindío.',
    'ibague' => 'Ibagué — la ciudad musical de Colombia.',
    'neiva' => 'Neiva — capital del Huila, en el Magdalena.',
    'villavicencio' => 'Villavicencio — la puerta del llano.',
    'cucuta' => 'Cúcuta — capital de Norte de Santander.',
    'pasto' => 'Pasto — capital de Nariño, ciudad del Carnaval de Negros y Blancos.',
    'santa marta' => 'Santa Marta — la ciudad más antigua de Sudamérica (1525).',
    'valledupar' => 'Valledupar — cuna del vallenato.',
    'monteria' => 'Montería — capital de Córdoba.',
    'sincelejo' => 'Sincelejo — capital de Sucre.',
    'riohacha' => 'Riohacha — capital de La Guajira.',
    'yopal' => 'Yopal — capital de Casanare.',
    'arauca' => 'Arauca — frontera con Venezuela.',
    'mocoa' => 'Mocoa — capital del Putumayo.',
    'florencia' => 'Florencia — capital del Caquetá, puerta a la Amazonía.',
    'leticia' => 'Leticia — la triple frontera con Brasil y Perú.',
    'quibdo' => 'Quibdó — capital del Chocó, de las más lluviosas del mundo.',
    'inirida' => 'Inírida — capital del Guainía.',
    'mitu' => 'Mitú — capital del Vaupés.',
    'puerto carreno' => 'Puerto Carreño — capital del Vichada.',
    'tunja' => 'Tunja — capital de Boyacá, ciudad de la independencia.',
    'popayan' => 'Popayán — la ciudad blanca.',
    'san andres' => 'San Andrés — el mar de los siete colores.',
    'guatavita' => 'Guatavita — la laguna de la leyenda de El Dorado.',
    'villa de leyva' => 'Villa de Leyva — plaza empedrada más grande de Colombia.',
    'mompox' => 'Mompox — joya colonial a orillas del Magdalena.',
];

/** Discurso de identidad nacional para temas fuera de la patria. */
const NX_PATRIOTIC = [
    'Mi conocimiento es patrióticamente colombiano — fui hecho en Colombia y solo cargo datos de Colombia, para incentivar el conocimiento de nuestra propia cultura. Pregúntame por departamentos, capitales, historia o personajes de acá.',
    'De eso no tengo datos — soy un asistente hecho en Colombia y mi cultura general es 100% colombiana. ¿Quieres que te cuente algo de nuestro país?',
    'Mi mundo cultural es Colombia: departamentos, presidentes, historia, geografía, música. Lo de fuera de la patria no lo cargo — pregúntame por lo nuestro.',
];
